name: LuRey Education
favicon: null
layout_spectrum: 0.99784
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fc8d25'
    - '#8c340d'
    - '#f4f3f1'
    - '#bfb5aa'
  brandStrength: 0.75
  lightness: 0.8106577831786126
  saturation: 0.4806749918498099
  rhythmicContrast: 0.5
purpose: []
